# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 495469af57454d3e60f4f614bf8042052e195f2c7fd10233b8801d921674125559e812a22bf8b8e1e53f0d18e65b19810a459b411cab46be2e6a743df2890388

test:
  secret_key_base: 52eff8f46101e0c551c40d5c44a44f1d54cab9bf4f3f73746597bbbd6791368490f4b5a701b4e65d63f74eb06d547482400b56f3253c6af6ffcb3402513f64f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
